token mint/burn actions
FlipsideCrypto/eclipse-models pull request #28
Opened 2024-10-10 04:24 UTC by tarikceric

Tables for `fact_token_burn_actions `and `fact_token_mint_actions`
- Similar to code in Solana tables, where there are some types of actions not yet present in Eclipse but maintained the same logic if they appear in the future

FR on Medium
```
04:23:07  1 of 7 OK created sql incremental model silver.burn_actions .................... [SUCCESS 1 in 4.42s]
04:23:07  2 of 7 OK created sql incremental model silver.mint_actions .................... [SUCCESS 1 in 4.68s]
04:23:13  3 of 7 OK created sql incremental model silver.mint_types ...................... [SUCCESS 1 in 5.81s]
04:23:16  4 of 7 OK created sql incremental model silver.token_burn_actions .............. [SUCCESS 1 in 3.46s]
04:23:17  5 of 7 OK created sql incremental model silver.token_mint_actions .............. [SUCCESS 1 in 3.66s]
04:23:20  7 of 7 OK created sql incremental model defi.fact_token_mint_actions ........... [SUCCESS 1 in 3.63s]
04:23:20  6 of 7 OK created sql incremental model defi.fact_token_burn_actions ........... [SUCCESS 1 in 3.83s]
```

Incremental on Medium
```
04:02:00  1 of 7 OK created sql incremental model silver.burn_actions .................... [SUCCESS 9526 in 8.56s]
04:02:00  2 of 7 OK created sql incremental model silver.mint_actions .................... [SUCCESS 18299 in 8.58s]
04:02:08  3 of 7 OK created sql incremental model silver.mint_types ...................... [SUCCESS 536 in 8.44s]
04:02:15  5 of 7 OK created sql incremental model silver.token_mint_actions .............. [SUCCESS 18233 in 7.04s]
04:02:16  4 of 7 OK created sql incremental model silver.token_burn_actions .............. [SUCCESS 9526 in 7.32s]
04:02:24  7 of 7 OK created sql incremental model defi.fact_token_burn_actions ........... [SUCCESS 9526 in 8.39s]
04:02:24  6 of 7 OK created sql incremental model defi.fact_token_mint_actions ........... [SUCCESS 18233 in 8.69s]
```

Tests
```
04:12:48  Finished running 126 data tests, 5 project hooks in 0 hours 1 minutes and 49.96 seconds (109.96s).
04:12:48  
04:12:48  Completed successfully
04:12:48  
04:12:48  Done. PASS=126 WARN=0 ERROR=0 SKIP=0 TOTAL=126
```

2024-10-15 16:54 UTC, desmond-hui requested changes

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/core/silver__burn_actions.sql
> +    )
nit: bad indents and some sql words are ALL caps some are lower case...They should all be uppercase

I think this is in all the models, so please fix accordingly

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/core/silver__mint_actions.yml
> +          - not_null: *recent_date_filter
missing `succeeded`

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/core/silver__burn_actions.yml
> +      - name: INDEX
missing `succeeded`

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/labels/silver__mint_types.sql
> +        program_id = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'
I am guessing this does not apply here

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/labels/silver__mint_types.sql
> +        program_id = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'
I am guessing this does not apply here

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/labels/silver__mint_types.sql
At a high level, I think this should be re-worked or simplified (NULL out or remove the meteplex dependent fields?) since it depends alot on metaplex which may not even exist in eclipse?

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/labels/silver__mint_types.yml
> +        description: "{{ doc('mint_standard_type') }}"
missing metadata fields

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/token/silver__token_mint_actions.sql
> +     A._inserted_timestamp,
nit: extra space

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/token/silver__token_burn_actions.sql
> +    cluster_by = ['block_timestamp::DATE','_inserted_timestamp::DATE'],
should think about clustering on `modified_timestamp` instead of `_inserted_timestamp` since that is what the gold tables use

2024-10-15 16:54 UTC, desmond-hui commented on models/silver/token/silver__token_mint_actions.sql
> +    cluster_by = ['block_timestamp::DATE','_inserted_timestamp::DATE'],
should think about clustering on `modified_timestamp` instead of `_inserted_timestamp` since that is what the gold tables use

2024-10-15 16:54 UTC, desmond-hui commented on models/gold/defi/defi__fact_token_burn_actions.sql
> +        token_burn_actions_id AS fact_token_burn_actions_id,
nit: extra indent

2024-10-15 16:54 UTC, desmond-hui commented on models/gold/defi/defi__fact_token_mint_actions.sql.yml
> +      - name: INDEX
missing `succeeded`

2024-10-15 16:54 UTC, desmond-hui commented on models/gold/defi/defi__fact_token_mint_actions.sql.yml
> +          - not_null: *recent_date_filter
cant use filter here

2024-10-15 16:54 UTC, desmond-hui commented on models/gold/defi/defi__fact_token_mint_actions.sql
> +        token_mint_actions_id AS fact_token_mint_actions_id,
nit: extra indent

2024-10-15 16:54 UTC, desmond-hui commented on models/gold/defi/defi__fact_token_burn_actions.yml
> +          - not_null: *recent_date_filter
can't use filter here

2024-10-15 18:41 UTC, tarikceric commented on models/silver/core/silver__burn_actions.yml
> +      - name: INDEX
added

2024-10-15 18:43 UTC, tarikceric commented on models/silver/labels/silver__mint_types.yml
> +        description: "{{ doc('mint_standard_type') }}"
added

2024-10-15 18:45 UTC, tarikceric commented on models/gold/defi/defi__fact_token_mint_actions.sql.yml
> +      - name: INDEX
added

2024-10-15 18:45 UTC, tarikceric commented on models/gold/defi/defi__fact_token_mint_actions.sql.yml
> +          - not_null: *recent_date_filter
removed

2024-10-15 18:45 UTC, tarikceric commented on models/gold/defi/defi__fact_token_burn_actions.yml
> +          - not_null: *recent_date_filter
removed

2024-10-15 19:07 UTC, tarikceric commented on models/silver/token/silver__token_burn_actions.sql
> +    cluster_by = ['block_timestamp::DATE','_inserted_timestamp::DATE'],
great point, added

2024-10-15 19:07 UTC, tarikceric commented on models/silver/token/silver__token_mint_actions.sql
> +    cluster_by = ['block_timestamp::DATE','_inserted_timestamp::DATE'],
updated

2024-10-15 19:42 UTC, tarikceric commented on models/silver/labels/silver__mint_types.sql
Metaplex events do exist in Eclipse, and seem to work in similar ways to Solana, besides not having some specific types of nfts like 'edition' but left that logic in case it does appear in the future.

2024-10-15 19:44 UTC, tarikceric commented on models/silver/core/silver__burn_actions.sql
> +    )
Generally cleaned up the formatting

2024-10-16 15:12 UTC, desmond-hui commented on models/silver/labels/silver__mint_types.sql
Well, TIL! Is it considered a native program? Should we expect other programs to name the same program_id in eclipse as they do in Solana?

2024-10-16 15:19 UTC, desmond-hui approved these changes

2024-10-16 15:19 UTC, desmond-hui commented on models/gold/defi/defi__fact_token_burn_actions.sql
> +) }}
Should these gold tables have additional meta tags?

2024-10-16 17:21 UTC, merged