add dim_labels
FlipsideCrypto/eclipse-models pull request #31
Opened 2024-11-04 23:57 UTC by tarikceric

Add `dim_labels`

- FR
```
23:44:55  1 of 2 OK created sql incremental model silver.labels .......................... [SUCCESS 1 in 4.94s]
23:44:57  2 of 2 OK created sql view model core.dim_labels ............................... [SUCCESS 1 in 2.39s]
```

- Test
`23:46:28  Finished running 9 data tests, 5 project hooks in 0 hours 0 minutes and 25.61 seconds (25.61s).`

2024-11-05 14:52 UTC, desmond-hui requested changes

2024-11-05 14:52 UTC, desmond-hui commented on models/gold/core/core__dim_labels.yml
> +      - name: LABEL
missing `address_name` in the schema

2024-11-05 14:52 UTC, desmond-hui commented on models/silver/labels/silver__labels.sql
> +    post_hook = "ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION ON EQUALITY(address); DELETE FROM {{ this }} WHERE _is_deleted = TRUE;",
use `enable_search_optimization` macro instead

2024-11-05 14:52 UTC, desmond-hui commented on models/silver/labels/silver__labels.sql
> +    SYSDATE() AS modified_timestamp,
nit: lowercase function names

2024-11-05 14:52 UTC, desmond-hui commented on models/silver/labels/silver__labels.sql
> +        MAX(
nit: lowercase function names

2024-11-05 14:52 UTC, desmond-hui commented on models/silver/labels/silver__labels.yml
> +          - not_null
Where are the rest of the column definitions?

2024-11-05 21:30 UTC, tarikceric commented on models/gold/core/core__dim_labels.yml
> +      - name: LABEL
updated

2024-11-05 21:30 UTC, tarikceric commented on models/silver/labels/silver__labels.sql
> +    post_hook = "ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION ON EQUALITY(address); DELETE FROM {{ this }} WHERE _is_deleted = TRUE;",
updated

2024-11-05 21:30 UTC, tarikceric commented on models/silver/labels/silver__labels.sql
> +    SYSDATE() AS modified_timestamp,
updated

2024-11-05 21:30 UTC, tarikceric commented on models/silver/labels/silver__labels.sql
> +        MAX(
updated

2024-11-05 21:30 UTC, tarikceric commented on models/silver/labels/silver__labels.yml
> +          - not_null
updated with rest of cols + tests

2024-11-05 21:33 UTC, tarikceric commented
Actually, should we be making the `dim_labels` view a table since thats we want for all gold?

2024-11-05 22:18 UTC, eric-laurello commented on models/gold/core/core__dim_labels.sql
> +AND modified_timestamp >= (
bad inc logic

2024-11-05 22:25 UTC, eric-laurello approved these changes

2024-11-06 14:36 UTC, desmond-hui approved these changes

2024-11-06 22:21 UTC, merged